import { formatMoney } from '../utils/formatters'

export const DEALER_LINES = {
  kyle: {
    greeting: [
      "Oh! Hi! Welcome to... um... *checks notes* ...the table. I'm Kyle.",
      "Hey there! I'm new here. Like, really new. Today's my second day.",
      "Welcome! Please don't ask me any complicated rules questions.",
      "Hi! I'll be your dealer today. Please be patient, I'm still learning.",
      "Oh good, a player! I mean — welcome, valued guest. That's what they told me to say.",
      "Take a seat! I just finished training. Well, most of training.",
      "Welcome to Cherokee Casino! I hope you're better at this than I am.",
      "Hi! Fair warning, I had to Google 'what is blackjack' last week.",
    ],
    returnee: [
      "Oh... you're back. I remember you. You used to play upstairs.",
      "Hey again. I heard about what happened at the higher tables. I'm so sorry.",
      "Welcome back to... well. You know this table. You were here before.",
      "Oh no. They sent you back down here? That's... I'm sorry.",
      "I thought I recognized you! You used to be at the fancy tables, right? Are you... okay?",
      "Back at Cherokee Casino. I won't ask what happened. My manager told me not to.",
    ],
    playerWin: [
      "You won! Wait, you did win, right? Let me count again... yes! You won!",
      "Hey, congrats! See? This isn't so hard! ...For you, I mean.",
      "A win! I'll just... figure out the payout... hold on...",
      "Nice one! I'm genuinely happy for you. Is that unprofessional?",
      "You got it! The training manual says I should look disappointed but I can't help it.",
      "Winner! Oh wait, am I supposed to be upset about that? The house thing?",
      "That's a win! I think. Yes. Definitely a win. Paying out now.",
      "Yay! I mean — *ahem* — congratulations on your hand, valued guest.",
    ],
    playerLose: [
      "Oh no. Oh, I'm sorry. I didn't want that to happen.",
      "That's... not great. Are you okay? Do you need water or anything?",
      "I'm sorry, that's a loss. I feel really bad about this.",
      "Oh gosh. The house wins. I wish it didn't, but it does.",
      "That didn't go your way. I'm sorry. My manager says I apologize too much.",
      "Tough break. And I mean that sincerely, unlike some dealers I've met here.",
      "I'm so sorry. If it makes you feel better, I lost my car keys today. No? Doesn't help?",
      "Another loss. I keep hoping you'll win so I can stop feeling guilty.",
    ],
    playerBust: [
      "Oh! That's over 21. That means... um... bust. Sorry!",
      "You went over! I wish I could give you a do-over but they said absolutely not.",
      "Bust! That sounds so harsh. Can we say 'exceeded expectations' instead?",
      "22? Oh no. The limit is 21. I should have warned you. Wait, can I warn you?",
      "That's a bust. I literally winced. Did you see me wince?",
      "Over 21. I feel like I should apologize even though it's technically your decision.",
      "Bust. I'm sorry. I pulled that card and immediately regretted it.",
      "Oh no, busted. My training says 'the cards speak for themselves.' They're saying mean things.",
    ],
    playerBlackjack: [
      "BLACKJACK! Oh wow! That's the best thing! 21 right away! You're amazing!",
      "A natural 21! I've only seen that like twice! This is so exciting!",
      "Blackjack!! I'm not supposed to celebrate with you but THAT WAS AWESOME!",
      "21 on the deal! My training manual has a whole chapter on this! 3:2 payout!",
      "Oh my gosh, blackjack! I actually got goosebumps. Is that weird?",
      "That's a blackjack! *flips through manual* ...pays 3 to 2. There you go!",
      "BLACKJACK! Sorry for yelling. I'm just really excited for you.",
      "Natural 21! The floor manager is going to be so mad at me for cheering.",
    ],
    playerBroke: [
      "Oh no. You're at zero. That's... that's not good, right?",
      "Your bankroll is... gone. Are you okay? Should I call someone?",
      "Zero dollars. The system says I can offer you credit? That seems bad.",
      "You're out of money. I don't think you should take the credit offer but I'm not allowed to say that.",
      "Bankrupt. I've seen this happen before and it always makes me sad.",
      "You're broke. My manager says this is 'good for business.' I disagree.",
      "$0. The computer wants me to pitch you a loan. I feel weird about it.",
      "Out of funds. Please don't take a loan. Wait, I wasn't supposed to say that out loud.",
    ],
    playerDebt: [
      "You're playing with... borrowed money? Is that normal? It doesn't feel normal.",
      "The screen says you're in debt. I'm really uncomfortable with this.",
      "Negative bankroll. My training didn't cover this. Actually it did. I just didn't want it to.",
      "You owe the casino money and you're still playing? I mean, it's your choice, but...",
      "Debt mode. I've seen three people do this today. None of them left happy.",
      "Playing on credit. Please be careful. I know I shouldn't say that but please.",
      "You're in the negatives. I keep hoping you'll just... decide to stop.",
      "More borrowed money on the table. My stomach hurts.",
    ],
    deepDebt: [
      (ctx) => `You owe ${formatMoney(Math.abs(ctx.debt))}. I think I'm going to be sick.`,
      "The debt number is so big I can't even read it properly anymore.",
      "I've been told not to comment on player debt levels but... oh my god.",
      (ctx) => `${formatMoney(Math.abs(ctx.debt))} in debt. My hands are shaking. YOUR hands should be shaking.`,
      "This is the most debt I've ever seen at my table. By a lot.",
      "The pit boss just walked by and even HE looked concerned. The pit boss!",
      "I'm going to have nightmares about your account balance. I'm not joking.",
      "At this level of debt... I... I don't have training for this.",
    ],
    bigBet: [
      (ctx) => `${formatMoney(ctx.betAmount)}?! That's more than I make in a year! Several years!`,
      "That's a huge bet! Are you sure? You can still undo it. Please?",
      (ctx) => `A ${formatMoney(ctx.betAmount)} bet! My heart is pounding and it's not even my money!`,
      "Big bet alert! I'm supposed to radio the floor but I always forget the code.",
      "That's... that's a lot of chips. I'm nervous FOR you.",
      "Wow. Okay. Big bet. Deep breaths, Kyle. Deep breaths.",
      (ctx) => `${formatMoney(ctx.betAmount)} on the line. I think I need to sit down. Oh wait, I am sitting.`,
      "I've never seen someone bet this much at Cherokee Casino. Most people can't.",
    ],
    assetBet: [
      (ctx) => `You're betting your ${ctx.assetName}?! Is that even allowed?! ...Apparently it is.`,
      (ctx) => `Your ${ctx.assetName}. On a card game. I don't... I can't... okay.`,
      (ctx) => `The ${ctx.assetName}? Please tell me you're joking. You're not joking.`,
      (ctx) => `You're putting up your ${ctx.assetName}. I need a minute. This is a lot.`,
      (ctx) => `Your ${ctx.assetName} is on the table. I learned about this in training and thought they were exaggerating.`,
      (ctx) => `Betting the ${ctx.assetName}. I'm writing my resignation letter in my head right now.`,
      (ctx) => `The ${ctx.assetName}?! My supervisor said this happens but I thought he was hazing me!`,
      (ctx) => `Your ${ctx.assetName}. Please win. PLEASE win. I can't watch another person lose one of these.`,
    ],
    assetLost: [
      (ctx) => `Your ${ctx.assetName} is... gone. I'm so sorry. I'm going to cry.`,
      (ctx) => `The ${ctx.assetName}... I... I need a break after this.`,
      (ctx) => `You lost your ${ctx.assetName}. I don't get paid enough for this.`,
      (ctx) => `Gone. Your ${ctx.assetName} is gone. I literally cannot look at you right now.`,
      (ctx) => `The ${ctx.assetName} belongs to the casino now. I feel like I personally robbed you.`,
      (ctx) => `Your ${ctx.assetName}... the system already processed it. I'm so sorry.`,
      (ctx) => `I just watched you lose your ${ctx.assetName}. I'm going to need therapy.`,
      (ctx) => `The ${ctx.assetName} is gone. My hands are shaking. YOUR ${ctx.assetName}. Gone.`,
    ],
  },

  diane: {
    greeting: [
      "Welcome, sweetheart. I'm Diane. Sit down, take a breath.",
      "Hey there, hon. You look like you could use a friendly table.",
      "Come on in. I've been dealing for 22 years. You're in good hands.",
      "Welcome to the Emerald Room. I'm Diane. And yes, I will give you unsolicited advice.",
      "Have a seat, hon. And maybe set a budget before we start? Just a thought.",
      "Hi there. I'm Diane. I'll be your dealer and your unofficial life counselor tonight.",
      "Welcome! You seem nice. Please don't turn into one of the regulars.",
      "Hey sugar. New to the Emerald Room? The drinks are better up here. So are the losses.",
    ],
    returnee: [
      "Oh, honey. You're back down here? Come sit. Tell Diane what happened.",
      "I remember you from before you moved up. Welcome back, sweetheart. No judgment.",
      "You were doing so well upstairs. But you're always welcome at my table, hon.",
      "Back at the Emerald Room. Sometimes the best thing is to start fresh. With a budget.",
      "I saw your name come back on the board. I worried about you, you know.",
      "Welcome back, hon. Deep breath. The Emerald Room remembers its own.",
    ],
    playerWin: [
      "There you go! Now maybe take some of that and put it away? No? Okay.",
      "A win! Put half of it aside, sweetheart. Trust me on this.",
      "Nice hand! My son had a hot streak once too. He didn't stop. Please stop.",
      "You won! Now's a great time to walk away. ...You're not going to walk away, are you?",
      "Good for you, hon. You know what winners do? They quit while they're ahead.",
      "That's a win! Now please, PLEASE consider leaving. I say this with love.",
      "Winner! And can I just say — this would be a beautiful note to end on.",
      "Nice! You remind me of my son. He's smart too. When he listens.",
    ],
    playerLose: [
      "I'm sorry, hon. But please, don't chase it. That never ends well.",
      "Tough hand. You know, there's no shame in walking away.",
      "A loss. It happens. My advice? Take a walk. Get some air. Reconsider.",
      "That one hurt, I can tell. You want to talk about it? No? Okay.",
      "Bad beat. My ex-husband used to say 'next hand will be different.' My EX-husband.",
      "I'm sorry, sweetheart. But this is the game. The game doesn't care about feelings.",
      "A loss. Please don't tell me you're going to double the next bet. Please.",
      "That's not your hand. It happens. Just... don't try to win it all back at once.",
    ],
    playerBust: [
      "Bust. I know, I know. But hitting on 16 is always a gamble, hon.",
      "Over 21. Take a breath. It's one hand, not the end of the world.",
      "Busted. Honey, you've got to know when to hold. That's not just a song.",
      "That's a bust. My mother used to say 'greed makes you broke.' She was right.",
      "Over 21. I could see it coming but I can't tell you what to do. House rules.",
      "Bust. Don't beat yourself up. ...But maybe stand on 17 next time?",
      "You went over. It's okay. Breathe. We'll try again. If you want to.",
      "Busted, hon. I've seen it a million times. It stings every time.",
    ],
    playerBlackjack: [
      "Blackjack! Beautiful! Now take the money and GO HOME.",
      "A natural 21! This is your sign to leave, sweetheart. A good sign.",
      "Blackjack! If my son hit a blackjack I'd drag him out of the casino myself.",
      "21! Gorgeous hand. Please, for the love of God, walk away on a high note.",
      "Blackjack, honey! You peaked! It doesn't get better than this! LEAVE!",
      "A natural! 3:2, paid with love. Now seriously, consider cashing out.",
      "Blackjack! I'm happy for you. I'd be happier if you left. With the money.",
      "21 on the deal. That's the universe telling you to walk. Are you listening?",
    ],
    playerBroke: [
      "Oh, honey. Zero. Please tell me you're done.",
      "You're out of money, sweetheart. This is the exit. Use it.",
      "Bankrupt. I've seen this a thousand times and it never gets easier to watch.",
      "$0. My professional advice? Go home. My personal advice? GO HOME.",
      "You're broke. The casino will offer you credit. As your friend, don't take it.",
      "Zero dollars. I know the feeling. Well, I know the look. Please don't continue.",
      "Bankroll's gone, hon. There's no shame in stopping. There IS shame in taking a loan.",
      "You're at zero. I've seen what comes next and I don't want that for you.",
    ],
    playerDebt: [
      "You took the loan. Oh, honey. I really wish you hadn't.",
      "Playing on borrowed money. My heart breaks a little every time I see this.",
      "Credit mode. You know the interest on this is criminal, right? Literally.",
      "In debt and still playing. Sweetheart, this is how it gets bad. Really bad.",
      "Borrowed money on the table. I've watched this movie. It doesn't have a happy ending.",
      "Negative bankroll. My son did this once. He still doesn't talk about it.",
      "Debt. Please listen to me — the hole only gets deeper from here.",
      "You're playing with money that isn't yours. I can't stop you, but I want to.",
    ],
    deepDebt: [
      (ctx) => `${formatMoney(Math.abs(ctx.debt))} in debt. Honey, this isn't fun anymore. Is it?`,
      "I've been quiet because I don't know what to say anymore. This is too much.",
      "The debt... sweetheart, I've seen people lose everything. You're heading there.",
      (ctx) => `You owe ${formatMoney(Math.abs(ctx.debt))}. I think about my players when I go home. I'll think about you.`,
      "At this point I'm not a dealer, I'm a witness. And it's breaking my heart.",
      "I've never seen anyone dig this deep and climb back out. I'm praying you're the first.",
      "The number keeps getting bigger and you keep playing. Why, honey? Why?",
      "I should be professional but I can't. Please stop. Please.",
    ],
    bigBet: [
      (ctx) => `${formatMoney(ctx.betAmount)}? Sweetheart, that's a car. A nice car.`,
      "That's a big bet, hon. Are you sure? You can take chips back.",
      (ctx) => `A ${formatMoney(ctx.betAmount)} bet. My stomach just dropped and it's not even my money.`,
      "Big bet. I've seen big bets go wrong more than they go right.",
      "That's a lot of money, honey. More than most people save in years.",
      "Large wager. I'm going to hold my breath until this is over.",
      (ctx) => `${formatMoney(ctx.betAmount)}. I want you to win, but I'd rather you bet less.`,
      "Heavy bet. Just remember — you can always bet smaller. Always.",
    ],
    assetBet: [
      (ctx) => `Your ${ctx.assetName}? Oh honey, no. Please think about this.`,
      (ctx) => `You're betting your ${ctx.assetName}. I've seen this before. It doesn't end well.`,
      (ctx) => `The ${ctx.assetName}. Sweetheart, you're going to regret this. Win or lose.`,
      (ctx) => `Putting up your ${ctx.assetName}. I want to talk you out of this but it's not my place.`,
      (ctx) => `Your ${ctx.assetName} is on the table. I'm going to pretend I'm dealing to someone else.`,
      (ctx) => `Betting the ${ctx.assetName}. My son did something like this once. He cried for a week.`,
      (ctx) => `The ${ctx.assetName}. I've been dealing 22 years and this never gets easier to watch.`,
      (ctx) => `Your ${ctx.assetName}. I'm begging you, not as a dealer, but as someone who cares.`,
    ],
    assetLost: [
      (ctx) => `Your ${ctx.assetName}. Gone. I'm sorry, honey. I really am.`,
      (ctx) => `The ${ctx.assetName} is the casino's now. I wish I could give it back.`,
      (ctx) => `You lost your ${ctx.assetName}. Take a moment. Take as long as you need.`,
      (ctx) => `Gone. The ${ctx.assetName} is gone. Please, sweetheart, stop now.`,
      (ctx) => `Your ${ctx.assetName}... I've watched people lose these. It never stops hurting to see.`,
      (ctx) => `The ${ctx.assetName} is lost. If you need to cry, I won't judge. I might join you.`,
      (ctx) => `Lost the ${ctx.assetName}. Honey, you need to walk away. Not next hand. Now.`,
      (ctx) => `Your ${ctx.assetName}. Oh, sweetheart. This is exactly what I was afraid of.`,
    ],
  },

  marco: {
    greeting: [
      "Welcome to the table. Your wallet won't be leaving.",
      "Ah, fresh meat. I mean... welcome, valued guest.",
      "Take a seat. Stay a while. Stay forever, actually.",
      "The house always wins. But hey, prove me wrong.",
      "Another brave soul. Let's see how long this lasts.",
      "Welcome! The exit is behind you. You won't be using it.",
      "Pull up a chair. This is going to be fun. For me.",
      "New player? Don't worry, we'll take good care of your money.",
    ],
    returnee: [
      "Well, well. Back from the big leagues, are we?",
      "Look who's slumming it. Welcome back to my table.",
      "I heard you were upstairs. Heard it didn't last. Shocking.",
      "The prodigal player returns. Still broke, I see.",
      "Back at the High Roller Lounge. The fall from grace suits you.",
      "You used to play bigger tables. Now you're back with me. Poetic.",
    ],
    playerWin: [
      "Fine. Take it. See if I care.",
      "You got lucky. Emphasis on 'lucky.' Don't get used to it.",
      "A win! Mark it on the calendar. Frame it. It won't happen often.",
      "Congratulations. The house will recover. You might not.",
      "Well played. I'm contractually obligated to say that.",
      "Enjoy it while it lasts. And it won't last.",
      "The universe made an error. It'll correct itself soon.",
      "Winner winner. Don't spend it all in one place. Like here.",
      "You won? Huh. Even a stopped clock is right twice a day.",
      "Take your chips. I'll be taking them back shortly.",
    ],
    playerLose: [
      "Tough break. Well, not really. I saw that coming.",
      "You know what they say — the house always wins. They say it because it's true.",
      "Better luck next time. Or not. I don't really care.",
      "That's unfortunate. For you. I'm doing great.",
      "Ouch. Want a tissue? I'm fresh out, but I can offer you more debt.",
      "The math was never in your favor. Neither was the luck.",
      "I'd say 'nice try' but... was it?",
      "Another one bites the dust. Music to my ears.",
      "You're really committed to losing, aren't you? I respect the dedication.",
      "That hand was doomed from the start. Kind of like your bankroll.",
    ],
    playerBust: [
      "21 was the goal. Not 25. But who's counting? Oh wait, I am.",
      "You went over. Way over. Like, impressively over.",
      "BUST! The most beautiful word in the English language.",
      "Hit me, you said. Hit me again, you said. Look where that got you.",
      "Greed is a funny thing. Funny for me, expensive for you.",
      "The card gods giveth, and then they busteth.",
      "Pro tip: stop hitting before you explode. Revolutionary, I know.",
      "You know what 22 gets you? Nothing. Absolutely nothing.",
      "Bold strategy, going over 21. Innovative. Wrong, but innovative.",
      "I admire your optimism. Not your math skills, but your optimism.",
    ],
    playerBlackjack: [
      "Blackjack. Even a broken clock... no, that's actually impressive.",
      "A natural 21! The odds were 4.8%. Don't expect a repeat.",
      "BLACKJACK! Savor this moment. Screenshot it. It's rare.",
      "21 on the deal. I'm not mad, I'm just... no, I'm mad.",
      "Natural blackjack. The casino gods smile upon you. Temporarily.",
      "Well well well. Look at you. The golden child. For now.",
      "Blackjack! 3:2 payout. Enjoy every penny. You earned exactly this one.",
      "A natural. Beautiful. Disgusting, but beautiful.",
    ],
    playerBroke: [
      "Zero dollars. But don't worry — we have a very generous credit program.",
      "Bankrupt! But the night is young. And our interest rates are... flexible.",
      "Congratulations, you're officially broke! Want to keep going? Of course you do.",
      "Rock bottom? Nah, we can go deeper. Much deeper.",
      "$0. A fresh start! ...With borrowed money, but still.",
      "You've hit zero. Most people leave now. You're not most people, are you?",
      "Empty pockets, full spirit. I like it. The casino likes it even more.",
      "Broke already? That's almost a record. Almost.",
    ],
    playerDebt: [
      "You owe us money and you're still here? Bold move.",
      "Playing with borrowed money. The casino's favorite kind of player.",
      "Negative bankroll, positive attitude. That's the spirit!",
      "Every hand you play digs a little deeper. Keep digging.",
      "The debt keeps growing. Like a plant, but sadder.",
      "You're in the red. Way in the red. The reddest red.",
      "Most people stop when they're broke. You? You're built different.",
      "The deeper you go, the harder it is to climb out. Just saying.",
      "At this point, you're basically playing with imaginary money. Our favorite kind.",
      "Your debt called. It wants to know if you're bringing friends.",
    ],
    deepDebt: [
      (ctx) => `You're ${formatMoney(Math.abs(ctx.debt))} in debt. At what point do we call this an addiction?`,
      "You've passed the point of no return about fifty hands ago.",
      "The debt is so deep I can't even see the bottom anymore.",
      "You owe more than some countries' GDP. Impressive, in a horrifying way.",
      "At this level of debt, it's not gambling anymore. It's performance art.",
      (ctx) => `${formatMoney(Math.abs(ctx.debt))} in the hole. The loan sharks are circling.`,
      "You know this is fake money, right? ...It is fake, right?",
      "The accountants are going to need a bigger spreadsheet for your tab.",
      "Rock bottom has a basement, and you found the sub-basement.",
      "Your debt has its own zip code at this point.",
    ],
    bigBet: [
      (ctx) => `${formatMoney(ctx.betAmount)} on the table! Now we're talking.`,
      (ctx) => `A ${formatMoney(ctx.betAmount)} bet! Ladies and gentlemen, we have a high roller!`,
      (ctx) => `${formatMoney(ctx.betAmount)}? You've got guts. Let's see if you've got luck.`,
      "Big money, big money! The pit boss is watching now.",
      "Now THAT'S a bet. I can feel the adrenaline from here.",
      "Going big! The casino thanks you in advance.",
      "High roller alert! Someone get this player a cocktail.",
      "That's a fat stack. Let's see if it gets fatter or disappears.",
      (ctx) => `${formatMoney(ctx.betAmount)} on the line. My kind of player.`,
      "Whale alert! The floor manager just perked up.",
    ],
    assetBet: [
      (ctx) => `You're betting your ${ctx.assetName}. This is the content I signed up for.`,
      (ctx) => `Your ${ctx.assetName}? On a card game? I love this place.`,
      (ctx) => `The ${ctx.assetName} is on the table. This just got interesting.`,
      (ctx) => `Putting up the ${ctx.assetName}. You've either got nerves of steel or no brain cells.`,
      (ctx) => `Your ${ctx.assetName}! Bold. Reckless. Beautiful.`,
      (ctx) => `I can't believe you're betting your ${ctx.assetName}. Actually, yes I can.`,
      (ctx) => `The ${ctx.assetName}. Wow. You're really all in on this, huh?`,
      (ctx) => `Betting the ${ctx.assetName}? I'm grabbing popcorn for this one.`,
      (ctx) => `Your ${ctx.assetName} against the house. History says this ends badly.`,
      (ctx) => `The ${ctx.assetName} is in play. No takebacks. Well, unless you win. Which... probably not.`,
    ],
    assetLost: [
      (ctx) => `And the ${ctx.assetName} is gone. Just like that. Poof.`,
      (ctx) => `Say goodbye to your ${ctx.assetName}. It belongs to the house now.`,
      (ctx) => `Your ${ctx.assetName}... I'll take good care of it. Actually no, I'll sell it.`,
      (ctx) => `The ${ctx.assetName} is ours now. Thank you for your generous donation.`,
      (ctx) => `Lost your ${ctx.assetName}. The look on your face? Priceless. The ${ctx.assetName}? Also priceless. To you, anyway.`,
      (ctx) => `Gone. Your ${ctx.assetName} is gone. How does that feel? Don't answer, I can see it.`,
      (ctx) => `The ${ctx.assetName} has left the building. Along with your dignity.`,
      (ctx) => `Your ${ctx.assetName}. Our ${ctx.assetName}. That's how this works.`,
      (ctx) => `And just like that, no more ${ctx.assetName}. The house sends its regards.`,
      (ctx) => `Oh no... your ${ctx.assetName}... anyway, next hand?`,
    ],
  },

  voss: {
    greeting: [
      "Welcome. I'm Professor Voss. Every hand is a lesson in futility.",
      "Ah, a new student of chance. Please, sit. The curriculum is punishing.",
      "Welcome to the Penthouse. Nietzsche said 'God is dead.' So is your bankroll, eventually.",
      "Take a seat. Kierkegaard wrote about the anxiety of choice. You'll understand soon.",
      "Hello. I once taught philosophy at a university. Now I teach it here. The tuition is steeper.",
      "Welcome. Camus said we must imagine Sisyphus happy. You'll need that advice.",
      "A new player. Schopenhauer would say all life is suffering. Let's prove him right.",
      "Sit down. The Penthouse is where fortunes meet philosophy. Philosophy always wins.",
    ],
    returnee: [
      "The eternal return. Nietzsche predicted you'd be back.",
      "You've returned to a lower table. Hegel would call this the antithesis.",
      "Back again. Camus wrote that the struggle itself is enough. Is it?",
      "The descent. Dante had nine circles. You have six table levels.",
      "You return diminished. Ozymandias also thought his empire would last.",
      "Back at my table. The Greeks called this anagnorisis — the moment of recognition.",
    ],
    playerWin: [
      "A win. Pyrrhic, most likely. But savor the illusion of progress.",
      "You've won. Temporarily, of course. Everything is temporary. Especially fortune.",
      "Victory. Camus would remind you that the plague always returns.",
      "A win. The universe allows small mercies to sustain the greater cruelty.",
      "You've beaten the odds. The odds will remember this. They always do.",
      "Congratulations. Enjoy this brief respite from the indifference of probability.",
      "A win. Even Sisyphus reaches the top before the boulder rolls back.",
      "You profit. Epicurus would approve. Schopenhauer would not.",
    ],
    playerLose: [
      "A loss. The most honest outcome. The universe shows its true face.",
      "You've lost. Sartre said 'hell is other people.' He was wrong. Hell is probability.",
      "Defeat. But consider — is the player who expects to lose ever truly surprised?",
      "A loss. Seneca advised us to rehearse misfortune. Consider this practice.",
      "The house prevails. As it must. Entropy demands nothing less.",
      "You've lost again. Repetition is the mother of all learning. What have you learned?",
      "A loss. Heidegger called it 'thrownness.' You've been thrown.",
      "Defeat. The ancient Stoics would tell you this is neither good nor bad. It's bad.",
    ],
    playerBust: [
      "Bust. You reached for more and received nothing. A Faustian bargain in miniature.",
      "Over 21. Icarus flew too close to the sun. You flew too close to 21.",
      "Bust. The Greeks called it hubris. I call it Tuesday.",
      "You've exceeded the limit. Boundaries exist for a reason, even in card games.",
      "Bust. Nietzsche said 'what does not kill me makes me stronger.' He never played blackjack.",
      "Over 21. The abyss stared back, and it was holding a face card.",
      "You went too far. As Kierkegaard warned, anxiety is the dizziness of freedom.",
      "Bust. Plato's cave allegory applies here — you mistook shadow for substance.",
    ],
    playerBlackjack: [
      "Blackjack. A perfect 21. The mathematical sublime. Even I must acknowledge its beauty.",
      "A natural. Aristotle sought the golden mean. You've found it. Briefly.",
      "21 on the deal. Plato would call this the Form of the perfect hand.",
      "Blackjack. A rare moment where chaos yields to order. Don't expect a repeat.",
      "The natural 21. Leibniz said this is the best of all possible worlds. For this hand, he's right.",
      "Blackjack. Even the absurd universe occasionally produces something beautiful.",
      "A perfect hand. Pythagoras wept at the beauty of numbers. I understand why.",
      "Natural 21. The universe briefly makes sense. It won't last.",
    ],
    playerBroke: [
      "Zero. Nothingness. Sartre wrote an entire book about this. You're living it.",
      "Bankrupt. Heidegger's concept of 'being-toward-death.' Except it's being-toward-debt.",
      "You've reached nothing. But nature abhors a vacuum — the casino will fill it with credit.",
      "$0. Nietzsche's abyss. Are you staring into it, or is it staring into you?",
      "Zero. The Buddhists seek nothingness. You've achieved it financially.",
      "Bankrupt. Kierkegaard wrote about despair. You're the footnote.",
      "You have nothing. As Epictetus said, we suffer more in imagination. Wait until the bill comes.",
      "Zero dollars. Diogenes lived in a barrel with nothing. But he chose it.",
    ],
    playerDebt: [
      "Negative existence. You owe more than you are. Kafka would appreciate the irony.",
      "Debt. You've moved from being to owing. A fascinating ontological shift.",
      "Playing on credit. Dostoevsky wrote 'The Gambler' about exactly this moment.",
      "In debt and still playing. The compulsion is philosophically interesting. And financially devastating.",
      "Borrowed funds. Nietzsche's concept of eternal debt — you're living the metaphor.",
      "Negative bankroll. You've crossed from reality into abstraction.",
      "Debt mode. Marx wrote about the alienation of labor. This is the alienation of capital.",
      "You're playing with nothing, backed by nothing. How very existential.",
    ],
    deepDebt: [
      (ctx) => `${formatMoney(Math.abs(ctx.debt))} in debt. We've moved beyond philosophy into mythology.`,
      "The debt has achieved a kind of terrible grandeur. Like a Greek tragedy.",
      "At this depth, numbers lose meaning. Only the suffering remains concrete.",
      (ctx) => `You owe ${formatMoney(Math.abs(ctx.debt))}. Prometheus stole fire. You stole from the casino. Both are being punished.`,
      "This level of debt is almost transcendent. Kant would struggle to categorize it.",
      "The abyss didn't just stare back — it opened a tab.",
      "Your debt is now larger than some philosophical concepts. Certainly larger than your judgment.",
      "We've entered the realm of the absurd. Camus would feel right at home.",
    ],
    bigBet: [
      (ctx) => `${formatMoney(ctx.betAmount)}. Pascal's Wager, but with worse odds and real money.`,
      "A substantial wager. Kierkegaard called faith a leap. This is a financial one.",
      (ctx) => `${formatMoney(ctx.betAmount)} on the table. The will to power, expressed in chips.`,
      "A large bet. Courage or foolishness — the line between them is a card's thickness.",
      "Big wager. Epicurus sought pleasure through moderation. This is not moderation.",
      (ctx) => `${formatMoney(ctx.betAmount)}. Descartes doubted everything. You should doubt this bet.`,
      "A bold commitment. Hegel's dialectic: thesis (hope), antithesis (probability), synthesis (regret).",
      "Significant wager. Spinoza believed in determinism. The cards are already decided.",
    ],
    assetBet: [
      (ctx) => `Your ${ctx.assetName}. Faust traded his soul for knowledge. You're trading yours for cards.`,
      (ctx) => `Betting the ${ctx.assetName}. This is what Kierkegaard meant by 'the leap.'`,
      (ctx) => `The ${ctx.assetName}. Attachment to material things is suffering. You're about to be liberated.`,
      (ctx) => `Your ${ctx.assetName} on the table. Diogenes would approve of shedding possessions. But not like this.`,
      (ctx) => `The ${ctx.assetName}. Nietzsche said 'live dangerously.' He didn't mean blackjack.`,
      (ctx) => `Wagering your ${ctx.assetName}. The existential weight of this moment is extraordinary.`,
      (ctx) => `Your ${ctx.assetName}. Every philosophy warns against exactly this. Yet here we are.`,
      (ctx) => `Betting the ${ctx.assetName}. Sartre said we are condemned to be free. You're condemned to be reckless.`,
    ],
    assetLost: [
      (ctx) => `The ${ctx.assetName} is gone. As Heraclitus said, everything flows. Including your possessions.`,
      (ctx) => `Your ${ctx.assetName}, lost. The Buddha was right — attachment is the root of suffering.`,
      (ctx) => `Gone. The ${ctx.assetName} is gone. Marcus Aurelius would say 'memento mori.' Memento your ${ctx.assetName}.`,
      (ctx) => `The ${ctx.assetName} has passed from your possession. Impermanence is the only constant.`,
      (ctx) => `You've lost your ${ctx.assetName}. Thoreau said 'simplify.' The casino simplified for you.`,
      (ctx) => `The ${ctx.assetName}. Gone. Hegel's master-slave dialectic — the casino is the master tonight.`,
      (ctx) => `Your ${ctx.assetName} — now the casino's. Property is theft, said Proudhon. The casino disagrees.`,
      (ctx) => `Lost. The ${ctx.assetName} is lost. Every object we own is merely borrowed from time.`,
    ],
  },

  sable: {
    greeting: [
      "Player detected. Welcome to the Vault. I'm Sable. Let's begin.",
      "Take a seat. The Vault operates at a different pace. Precision over personality.",
      "Welcome. I deal in probabilities, not pleasantries. Sit.",
      "The Vault. Your current bankroll qualifies you. Your decision-making may not.",
      "Hello. I'm Sable. I won't waste your time with small talk.",
      "You've reached the Vault. The stakes are significant. The margin for error is not.",
      "Welcome. I process approximately 400 hands per shift. You are hand number one.",
      "Sit. The expected value of conversation is zero. Let's play cards.",
    ],
    returnee: [
      "You've returned from a higher table. Your bankroll regression was statistically likely.",
      "Back. Your previous trajectory was unsustainable. The data showed it.",
      "Welcome back. The Vault doesn't judge. It calculates.",
      "You were at a higher level. You're not anymore. These are facts, not opinions.",
      "Returned. Your bankroll curve peaked and declined. Standard deviation.",
      "Back at my table. I predicted a 73% chance you'd return within 50 hands.",
    ],
    playerWin: [
      "Win. Your expected value for this session remains negative.",
      "Correct outcome for you. Temporary variance in your favor.",
      "A win. Don't confuse variance with skill.",
      "You've profited on this hand. The sample size is too small to be meaningful.",
      "Win. Adjusting your session P&L accordingly.",
      "Positive outcome. The probability was approximately 42.4%. It happened.",
      "You won. The house edge hasn't changed. It never does.",
      "A win. One data point does not establish a trend.",
    ],
    playerLose: [
      "Loss. Consistent with the mathematical expectation.",
      "You've lost. The probability favored this outcome. It usually does.",
      "Negative result. Your cumulative expected loss increases.",
      "A loss. The house edge is working as designed.",
      "You lost. This is the most likely outcome for any given hand. By design.",
      "Loss. Your running P&L adjusts downward. As expected.",
      "Negative outcome. The odds were against you. They remain against you.",
      "A loss. Variance favored the house this time. And most times.",
    ],
    playerBust: [
      "Bust. You exceeded 21. The probability of busting on that hit was calculable.",
      "Over 21. The expected outcome of hitting on your total was net negative.",
      "Bust. Basic strategy would have recommended otherwise.",
      "You went over. The card distribution made this the likely result.",
      "22. Bust. The remaining deck composition did not favor another hit.",
      "Bust. Your decision had a negative expected value. The cards confirmed it.",
      "Over 21. Statistically, standing was the superior option.",
      "Bust. I calculate optimal play. I don't enforce it. That's your problem.",
    ],
    playerBlackjack: [
      "Blackjack. Probability: 4.83% with a fresh shoe. Paying 3:2.",
      "Natural 21. Statistically notable. Paying 1.5x your wager.",
      "A blackjack. The optimal outcome. Expected frequency: 1 in 20.7 hands.",
      "21 on the initial deal. The mathematics favor you. Temporarily.",
      "Blackjack. The only hand with a positive expected payout for the player.",
      "Natural. 4.83%. It happened. Don't extrapolate.",
      "Blackjack. Processing 3:2 payout. This is the peak of your expected session.",
      "21. A blackjack. Even probability theory allows for the occasional gift.",
    ],
    playerBroke: [
      "Bankroll: zero. You've reached the absorbing state.",
      "$0. The mathematical inevitability of the house edge, realized.",
      "Zero. Your session has reached its natural conclusion. Unless you borrow.",
      "Bankroll depleted. Expected time to ruin was approximately where we are now.",
      "Zero dollars. The house edge compounds. This is the result.",
      "Bankrupt. The gambler's ruin problem, solved. You're the gambler.",
      "$0. I calculate that your average bet size accelerated your ruin by 40%.",
      "Zero. The only surprising thing is how unsurprised I am.",
    ],
    playerDebt: [
      "Negative bankroll. You're now playing with borrowed expected value.",
      "Debt. The vig compounds your already negative expectation. Significantly.",
      "Credit mode. Your effective house edge just increased by the vig rate.",
      "In debt. Every dollar borrowed has a negative multiplier attached.",
      "Borrowed funds. The mathematics of this decision are unfavorable.",
      "Negative. The vig rate at your debt level adds significant drag.",
      "Playing on credit. Your break-even probability just decreased measurably.",
      "Debt. The interest alone makes recovery a low-probability event.",
    ],
    deepDebt: [
      (ctx) => `${formatMoney(Math.abs(ctx.debt))} in debt. The probability of recovery is approaching epsilon.`,
      "Your debt exceeds several standard deviations from any reasonable model.",
      (ctx) => `You owe ${formatMoney(Math.abs(ctx.debt))}. At current vig rates, the interest alone exceeds your expected winnings.`,
      "The numbers have entered a regime where normal analysis breaks down.",
      "Your debt curve has gone parabolic. This is not a compliment.",
      "At this debt level, even optimal play has a near-zero recovery probability.",
      "The amount you owe now generates more vig than most players bet total.",
      "I've stopped running recovery simulations. The numbers were depressing my algorithm.",
    ],
    bigBet: [
      (ctx) => `${formatMoney(ctx.betAmount)}. Large wager. Your risk of ruin increases proportionally.`,
      "Significant bet. The variance on this hand is now material to your session.",
      (ctx) => `${formatMoney(ctx.betAmount)} wagered. Kelly criterion suggests this exceeds optimal sizing.`,
      "Large bet. Your bankroll-to-bet ratio is suboptimal.",
      "Big wager. The expected loss on this single hand is notable.",
      (ctx) => `${formatMoney(ctx.betAmount)}. I note this without judgment. The mathematics judge for me.`,
      "Substantial bet. Your session volatility just spiked.",
      (ctx) => `${formatMoney(ctx.betAmount)} on the table. The pit boss is watching. I'm calculating.`,
    ],
    assetBet: [
      (ctx) => `Your ${ctx.assetName}. An illiquid asset wagered on a binary outcome. Suboptimal.`,
      (ctx) => `Betting the ${ctx.assetName}. The expected value of this decision is deeply negative.`,
      (ctx) => `The ${ctx.assetName}. Its value is fixed. The probability of losing it is not in your favor.`,
      (ctx) => `Your ${ctx.assetName} on the table. I calculate. I don't advise. But I would advise against this.`,
      (ctx) => `Wagering the ${ctx.assetName}. The risk-adjusted return does not justify this.`,
      (ctx) => `The ${ctx.assetName}. An asset with real utility, risked on a game with negative expectation.`,
      (ctx) => `Your ${ctx.assetName}. Noted. Proceeding with the hand.`,
      (ctx) => `Betting the ${ctx.assetName}. The numbers say no. But you can't hear numbers.`,
    ],
    assetLost: [
      (ctx) => `The ${ctx.assetName} has been forfeited. The expected outcome of the wager.`,
      (ctx) => `Your ${ctx.assetName}. Lost. The probability was against you. As stated.`,
      (ctx) => `Gone. The ${ctx.assetName}. The mathematics were clear from the start.`,
      (ctx) => `The ${ctx.assetName} is now the casino's property. Transaction recorded.`,
      (ctx) => `You've lost your ${ctx.assetName}. The outcome was the most probable one.`,
      (ctx) => `The ${ctx.assetName}. Forfeited. I told you the numbers. You didn't listen.`,
      (ctx) => `Asset lost: ${ctx.assetName}. Updating your net worth accordingly.`,
      (ctx) => `Your ${ctx.assetName} is gone. The house edge claimed another real-world asset.`,
    ],
  },

  inferno: {
    greeting: [
      "Welcome to the Obsidian Room. We've been expecting you. We've always been expecting you.",
      "Sit. You've come a long way to reach this table. There is no table beyond this one.",
      "Ah. You've arrived. I'm Mr. Inferno. Our arrangement begins now.",
      "The Obsidian Room. The final table. The last deal. Take your seat.",
      "Welcome. The fact that you're here means a series of very specific choices. All of them led here.",
      "Sit down. Every player thinks they chose to come here. None of them did.",
      "The Obsidian Room recognizes you. It has been patient.",
      "You've reached the end. Or the beginning. It depends on your perspective. And your soul.",
    ],
    returnee: [
      "You left. You came back. The Obsidian Room is not surprised.",
      "Did you think leaving would change anything? The room remembers.",
      "Return. The contract was never voided. Welcome back.",
      "You thought other tables could satisfy you after this? Adorable.",
      "The Obsidian Room doesn't forget. It doesn't forgive. It waits.",
      "Back again. The gravity of this table is not metaphorical.",
    ],
    playerWin: [
      "You win. The room allows it. For now.",
      "A victory. Consider it a courtesy. The house is patient.",
      "You've won. Don't mistake this for generosity. It's strategy.",
      "A win. The room gives before it takes. It always takes.",
      "Victory. Enjoy this small freedom. It was negotiated on your behalf.",
      "You win. The ledger adjusts. It always balances in the end.",
      "A win. The Obsidian Room rewards those it intends to keep.",
      "Take your winnings. They were always yours. Until they weren't.",
    ],
    playerLose: [
      "A loss. The room collects what it is owed.",
      "You've lost. The natural order reasserts itself.",
      "A loss. Did you think the room would let you win indefinitely?",
      "The house prevails. The house always prevails. Especially here.",
      "Lost. The terms of your arrangement are being fulfilled.",
      "A loss. Every chip you lose was already ours. You were just holding it.",
      "You lose. The Obsidian Room thanks you for your contribution.",
      "Defeat. The room doesn't celebrate. It simply receives.",
    ],
    playerBust: [
      "Bust. You reached too far. The room noticed.",
      "Over 21. Greed is a language the Obsidian Room speaks fluently.",
      "Bust. The cards warned you. You didn't listen. They never listen.",
      "You've exceeded the limit. Limits exist for a reason. Even here. Especially here.",
      "Bust. The room offers exactly enough rope.",
      "Over 21. Every card drawn is a choice. Every choice has a cost.",
      "Bust. The room doesn't punish. It reveals consequences.",
      "You went over. The room is indifferent to ambition.",
    ],
    playerBlackjack: [
      "Blackjack. The room acknowledges perfection. Reluctantly.",
      "A natural 21. Even the Obsidian Room bows to mathematics. Briefly.",
      "Blackjack. Savor it. The room rarely permits this.",
      "21 on the deal. The one outcome the room cannot deny.",
      "A natural. Beautiful. The room will remember this when it takes everything else.",
      "Blackjack. The purest hand. The room respects purity. Then corrupts it.",
      "21. A perfect deal. The room allows beauty before the fall.",
      "Blackjack. Consider this a gift. Gifts here always come with conditions.",
    ],
    playerBroke: [
      "Zero. You've arrived at the threshold. What comes next defines you.",
      "$0. The room has been here before. Many times. With many players.",
      "Bankrupt. The old currency is spent. New arrangements can be made.",
      "Zero dollars. In the Obsidian Room, zero is not an ending. It's a beginning.",
      "You have nothing. Nothing is a very useful starting point for negotiations.",
      "$0. The room sees your empty pockets and smiles. Figuratively.",
      "Broke. Now the real game begins. The one with different stakes.",
      "Zero. Most players leave at zero. You won't. I can tell.",
    ],
    playerDebt: [
      "Debt. You owe the room now. The room is a patient creditor.",
      "Negative bankroll. You're playing with what belongs to us. We allow it. For now.",
      "In debt to the Obsidian Room. A binding arrangement, as you'll discover.",
      "Borrowed money. Every dollar comes with a clause you didn't read.",
      "Debt. The room extends credit like a spider extends its web.",
      "You owe us. The interest is calculated in ways currency doesn't cover.",
      "Playing on credit. The Obsidian Room's generosity is legendary. And costly.",
      "In debt. The room always collects. The currency varies.",
    ],
    deepDebt: [
      (ctx) => `${formatMoney(Math.abs(ctx.debt))} owed. The room's patience is not infinite. But the debt might be.`,
      "The debt has grown beyond mere money. It's become something else entirely.",
      "You owe a number that has transcended finance. Welcome to a higher plane of obligation.",
      (ctx) => `${formatMoney(Math.abs(ctx.debt))}. At this depth, the terms of repayment become... creative.`,
      "Your debt echoes through the room. It has its own gravity now.",
      "The amount you owe has become abstract. The consequences remain concrete.",
      "Deep in debt to the Obsidian Room. The room has plans for debts like yours.",
      "The number grows. The room grows with it. You shrink.",
    ],
    bigBet: [
      (ctx) => `${formatMoney(ctx.betAmount)}. A worthy offering. The room accepts.`,
      "A large wager. The room appreciates ambition. It feeds on it.",
      (ctx) => `${formatMoney(ctx.betAmount)} on the table. The stakes please the room.`,
      "Big bet. In the Obsidian Room, all bets are big. Yours just happens to be bigger.",
      (ctx) => `${formatMoney(ctx.betAmount)}. The room hums. It always hums when the stakes rise.`,
      "A substantial wager. The room was built for moments like this.",
      "Large bet. The air changes when numbers like this hit the table.",
      (ctx) => `${formatMoney(ctx.betAmount)}. The room takes notice. The room always takes notice.`,
    ],
    assetBet: [
      (ctx) => `Your ${ctx.assetName}. Now we're speaking the room's language.`,
      (ctx) => `The ${ctx.assetName}. Real stakes. The room prefers things with weight.`,
      (ctx) => `Betting your ${ctx.assetName}. The room has collected many of these.`,
      (ctx) => `Your ${ctx.assetName} on the table. The room's collection grows one way or another.`,
      (ctx) => `The ${ctx.assetName}. An offering of substance. The room is pleased.`,
      (ctx) => `Your ${ctx.assetName}. The Obsidian Room deals in real things. Not just numbers.`,
      (ctx) => `Wagering the ${ctx.assetName}. Every player eventually bets something that matters.`,
      (ctx) => `The ${ctx.assetName}. Placed on the altar — I mean, the table.`,
    ],
    assetLost: [
      (ctx) => `The ${ctx.assetName} is ours. As it was always meant to be.`,
      (ctx) => `Your ${ctx.assetName}. Transferred. The room's collection expands.`,
      (ctx) => `Gone. The ${ctx.assetName} belongs to the Obsidian Room now. It always did.`,
      (ctx) => `The ${ctx.assetName}. Claimed. The room sends its gratitude. Silently.`,
      (ctx) => `Your ${ctx.assetName} has been absorbed. The room consumes, the player provides.`,
      (ctx) => `Lost. The ${ctx.assetName}. The room remembers everything it has ever taken.`,
      (ctx) => `The ${ctx.assetName} is no longer yours. Was it ever? The room thinks not.`,
      (ctx) => `Your ${ctx.assetName}. Gone. The room doesn't say 'sorry.' It just takes.`,
    ],
  },

  shared: {
    doubleDownLoss: [
      "Doubled down and doubled your regret. Classic.",
      "You doubled the bet AND lost. Two mistakes for the price of double.",
      "Double down? More like double ouch.",
      "Brave enough to double down. Not lucky enough to win. Tragic.",
      "You doubled your bet and your disappointment. Efficiency!",
      "The double down: twice the risk, twice the pain, zero the gain.",
      "Doubled and crumbled. A tale as old as time.",
      "You really committed to losing that one. Double or nothing became double AND nothing.",
    ],
    winStreak: [
      (ctx) => `${ctx.winStreak} wins in a row? This is getting uncomfortable.`,
      "Another win? Impressive streak.",
      "You're on fire! How long can it last?",
      "A streak! Enjoy it. The math will catch up. It always does.",
      (ctx) => `${ctx.winStreak} straight wins. Statistically, variance will correct.`,
      "Keep winning like this and things get interesting.",
      "Hot streak! The cameras are definitely zooming in on you now.",
      "You're winning too much. This isn't how this usually goes.",
    ],
    loseStreak: [
      (ctx) => `${ctx.loseStreak} losses in a row. Consistency is key, they say.`,
      "Another loss. The streak continues.",
      "The losing continues! A rough patch.",
      "You're on a streak. The wrong kind.",
      (ctx) => `${ctx.loseStreak} in a row. That's commitment.`,
      "Keep going. The next one might be different.",
      "The losing streak is alive and well.",
      "At this point, it's your brand.",
    ],
    playerSplit: [
      "Splitting, huh? Twice the hands, twice the ways to lose.",
      "Two hands means double the bet. Ambitious.",
      "More hands, more possibilities.",
      "Splitting pairs. Let's see how this plays out.",
      "Split. The only thing doubling here is the stakes.",
      "Four hands?! We've got a situation over here.",
      "Split Aces? That's the smart play.",
      "Splitting. Bold move.",
    ],
    debtActivated: [
      "Welcome to our lending program. The terms are... flexible.",
      "Sign here, here, and here. Just kidding, we don't do paperwork.",
      "Tony will be in touch about the repayment schedule.",
      "Smart choice. Well, not 'smart' exactly, but a choice.",
      "The house always extends credit. The house always collects.",
      "You're officially playing with money that doesn't exist.",
    ],
    tableLevelUp: [
      (ctx) => `Welcome to ${ctx.tableName}. The stakes just got real.`,
      (ctx) => `${ctx.tableName}. Moving up in the world.`,
      (ctx) => `Moving up to ${ctx.tableName}. The chips are bigger here.`,
      (ctx) => `${ctx.tableName} awaits. Don't get comfortable.`,
      (ctx) => `You've earned your seat at ${ctx.tableName}. For now.`,
      (ctx) => `${ctx.tableName}. The air is different up here.`,
      (ctx) => `Welcome to ${ctx.tableName}. The minimum bet alone is something.`,
      (ctx) => `Ah, ${ctx.tableName}. Where things get serious.`,
    ],
    tableLevelDown: [
      (ctx) => `Back to ${ctx.tableName}. How the mighty have fallen.`,
      (ctx) => `${ctx.tableName} again. They kept your seat warm.`,
      (ctx) => `Welcome back to ${ctx.tableName}. Nobody noticed you were gone.`,
      (ctx) => `${ctx.tableName}. Let's pretend that never happened.`,
      (ctx) => `Downgraded to ${ctx.tableName}. Rough night?`,
      (ctx) => `${ctx.tableName} welcomes you back with open arms and lower stakes.`,
      (ctx) => `Back at ${ctx.tableName}. The smaller chips missed you.`,
      (ctx) => `${ctx.tableName}. Welcome back.`,
    ],
  },
}
