import { formatMoney } from '../utils/formatters'

export const DEALER_LINES = {
  greeting: [
    "Welcome to the table. Your wallet won't be leaving.",
    "Ah, fresh meat. I mean... welcome, valued guest.",
    "Take a seat. Stay a while. Stay forever, actually.",
    "The house always wins. But hey, prove me wrong.",
    "Another brave soul. Let's see how long this lasts.",
    "Welcome! The exit is behind you. You won't be using it.",
    "Pull up a chair. This is going to be fun. For me.",
    "New player? Don't worry, we'll take good care of your money.",
    "The odds are in your favor. Just kidding. They never are.",
    "Let's play. I've got all night. Do you have all your savings?",
  ],

  playerLose: [
    "Tough break. Well, not really. I saw that coming.",
    "You know what they say — the house always wins. They say it because it's true.",
    "Better luck next time. Or not. I don't really care.",
    "That's unfortunate. For you. I'm doing great.",
    "Ouch. Want a tissue? I'm fresh out, but I can offer you more debt.",
    "The math was never in your favor. Neither was the luck.",
    "I'd say 'nice try' but... was it?",
    "Another one bites the dust. Music to my ears.",
    "You're really committed to losing, aren't you? I respect the dedication.",
    "That hand was doomed from the start. Kind of like your bankroll.",
  ],

  playerBust: [
    "21 was the goal. Not 25. But who's counting? Oh wait, I am.",
    "You went over. Way over. Like, impressively over.",
    "BUST! The most beautiful word in the English language.",
    "Hit me, you said. Hit me again, you said. Look where that got you.",
    "Greed is a funny thing. Funny for me, expensive for you.",
    "The card gods giveth, and then they busteth.",
    "Pro tip: stop hitting before you explode. Revolutionary, I know.",
    "You know what 22 gets you? Nothing. Absolutely nothing.",
    "Bold strategy, going over 21. Innovative. Wrong, but innovative.",
    "I admire your optimism. Not your math skills, but your optimism.",
  ],

  playerBroke: [
    "Zero dollars. But don't worry — we have a very generous credit program.",
    "Bankrupt! But the night is young. And our interest rates are... flexible.",
    "Congratulations, you're officially broke! Want to keep going? Of course you do.",
    "Rock bottom? Nah, we can go deeper. Much deeper.",
    "$0. A fresh start! ...With borrowed money, but still.",
    "You've hit zero. Most people leave now. You're not most people, are you?",
    "Empty pockets, full spirit. I like it. The casino likes it even more.",
    "Broke already? That's almost a record. Almost.",
  ],

  playerDebt: [
    "You owe us money and you're still here? Bold move.",
    "Playing with borrowed money. The casino's favorite kind of player.",
    "Negative bankroll, positive attitude. That's the spirit!",
    "Every hand you play digs a little deeper. Keep digging.",
    "The debt keeps growing. Like a plant, but sadder.",
    "You're in the red. Way in the red. The reddest red.",
    "Most people stop when they're broke. You? You're built different.",
    "The deeper you go, the harder it is to climb out. Just saying.",
    "At this point, you're basically playing with imaginary money. Our favorite kind.",
    "Your debt called. It wants to know if you're bringing friends.",
  ],

  assetBet: [
    (ctx) => `You're betting your ${ctx.assetName}. This is the content I signed up for.`,
    (ctx) => `Your ${ctx.assetName}? On a card game? I love this place.`,
    (ctx) => `The ${ctx.assetName} is on the table. This just got interesting.`,
    (ctx) => `Putting up the ${ctx.assetName}. You've either got nerves of steel or no brain cells.`,
    (ctx) => `Your ${ctx.assetName}! Bold. Reckless. Beautiful.`,
    (ctx) => `I can't believe you're betting your ${ctx.assetName}. Actually, yes I can.`,
    (ctx) => `The ${ctx.assetName}. Wow. You're really all in on this, huh?`,
    (ctx) => `Betting the ${ctx.assetName}? I'm grabbing popcorn for this one.`,
    (ctx) => `Your ${ctx.assetName} against the house. History says this ends badly.`,
    (ctx) => `The ${ctx.assetName} is in play. No takebacks. Well, unless you win. Which... probably not.`,
  ],

  playerWin: [
    "Fine. Take it. See if I care.",
    "You got lucky. Emphasis on 'lucky.' Don't get used to it.",
    "A win! Mark it on the calendar. Frame it. It won't happen often.",
    "Congratulations. The house will recover. You might not.",
    "Well played. I'm contractually obligated to say that.",
    "Enjoy it while it lasts. And it won't last.",
    "The universe made an error. It'll correct itself soon.",
    "Winner winner. Don't spend it all in one place. Like here.",
    "You won? Huh. Even a stopped clock is right twice a day.",
    "Take your chips. I'll be taking them back shortly.",
  ],

  playerBlackjack: [
    "Blackjack. Even a broken clock... no, that's actually impressive.",
    "A natural 21! The odds were 4.8%. Don't expect a repeat.",
    "BLACKJACK! Savor this moment. Screenshot it. It's rare.",
    "21 on the deal. I'm not mad, I'm just... no, I'm mad.",
    "Natural blackjack. The casino gods smile upon you. Temporarily.",
    "Well well well. Look at you. The golden child. For now.",
    "Blackjack! 3:2 payout. Enjoy every penny. You earned exactly this one.",
    "A natural. Beautiful. Disgusting, but beautiful.",
  ],

  bigBet: [
    (ctx) => `${formatMoney(ctx.betAmount)} on the table! Now we're talking.`,
    (ctx) => `A ${formatMoney(ctx.betAmount)} bet! Ladies and gentlemen, we have a high roller!`,
    (ctx) => `${formatMoney(ctx.betAmount)}? You've got guts. Let's see if you've got luck.`,
    "Big money, big money! The pit boss is watching now.",
    "Now THAT'S a bet. I can feel the adrenaline from here.",
    "Going big! The casino thanks you in advance.",
    "High roller alert! Someone get this player a cocktail.",
    "That's a fat stack. Let's see if it gets fatter or disappears.",
    (ctx) => `${formatMoney(ctx.betAmount)} on the line. My kind of player.`,
    "Whale alert! The floor manager just perked up.",
  ],

  doubleDownLoss: [
    "Doubled down and doubled your regret. Classic.",
    "You doubled the bet AND lost. Two mistakes for the price of... well, double.",
    "Double down? More like double ouch.",
    "Brave enough to double down. Not lucky enough to win. Tragic.",
    "You doubled your bet and your disappointment. Efficiency!",
    "The double down: twice the risk, twice the pain, zero the gain.",
    "Doubled and crumbled. A tale as old as time.",
    "You really committed to losing that one. Double or nothing became double AND nothing.",
  ],

  winStreak: [
    (ctx) => `${ctx.winStreak} wins in a row? This is getting uncomfortable.`,
    "Another win? The pit boss is giving me the look.",
    "You're on fire! Someone call security. I mean, the fire department.",
    "A streak! Enjoy it. The math will catch up. It always does.",
    (ctx) => `${ctx.winStreak} straight wins. Statistically, you're due for a crash.`,
    "Keep winning like this and I'll be the one in debt.",
    "Hot streak! The cameras are definitely zooming in on you now.",
    "You're winning too much. This isn't how this is supposed to go.",
    "I'm starting to sweat. Not because of you. It's... warm in here.",
    "The streak continues. The house does NOT like streaks.",
  ],

  loseStreak: [
    (ctx) => `${ctx.loseStreak} losses in a row. But who's counting? Oh right, the casino is.`,
    "Another loss? I'm so sorry. Just kidding, I'm not.",
    "The losing continues! Consistency is key, they say.",
    "You're on a streak! ...The wrong kind, but still.",
    (ctx) => `${ctx.loseStreak} in a row. That's commitment to a bit.`,
    "Keep going. I'm sure the next one will be different. It won't, but sure.",
    "The losing streak is alive and well. Just like my entertainment.",
    "At this point, losing is your brand. Own it.",
    "Have you considered... winning? Just a thought.",
    "L after L after L. You're collecting them like stamps.",
  ],

  assetLost: [
    (ctx) => `And the ${ctx.assetName} is gone. Just like that. Poof.`,
    (ctx) => `Say goodbye to your ${ctx.assetName}. It belongs to the house now.`,
    (ctx) => `Your ${ctx.assetName}... I'll take good care of it. Actually no, I'll sell it.`,
    (ctx) => `The ${ctx.assetName} is ours now. Thank you for your generous donation.`,
    (ctx) => `Lost your ${ctx.assetName}. The look on your face? Priceless. The ${ctx.assetName}? Also priceless. To you, anyway.`,
    (ctx) => `Gone. Your ${ctx.assetName} is gone. How does that feel? Don't answer, I can see it.`,
    (ctx) => `The ${ctx.assetName} has left the building. Along with your dignity.`,
    (ctx) => `Your ${ctx.assetName}. Our ${ctx.assetName}. That's how this works.`,
    (ctx) => `And just like that, no more ${ctx.assetName}. The house sends its regards.`,
    (ctx) => `Oh no... your ${ctx.assetName}... anyway, next hand?`,
  ],

  deepDebt: [
    (ctx) => `You're ${formatMoney(Math.abs(ctx.debt))} in debt. At what point do we call this an addiction?`,
    "You've passed the point of no return about fifty hands ago.",
    "The debt is so deep I can't even see the bottom anymore.",
    "You owe more than some countries' GDP. Impressive, in a horrifying way.",
    "At this level of debt, it's not gambling anymore. It's performance art.",
    (ctx) => `${formatMoney(Math.abs(ctx.debt))} in the hole. The loan sharks are circling.`,
    "You know this is fake money, right? ...It is fake, right?",
    "The accountants are going to need a bigger spreadsheet for your tab.",
    "Rock bottom has a basement, and you found the sub-basement.",
    "Your debt has its own zip code at this point.",
  ],

  playerSplit: [
    "Splitting, huh? Twice the hands, twice the ways to lose.",
    "Oh good, you want to lose FASTER.",
    "Two hands means double the bet. I love your ambition.",
    "More hands, more chances for me. I mean you. Definitely you.",
    "Splitting pairs? Bold move. Let's see how this plays out.",
    "The only thing you're doubling here is my entertainment.",
    "Split Aces? That's the smartest thing you've done all night. Don't get used to it.",
    "Four hands?! Someone call the pit boss, we've got a maniac over here.",
  ],
  debtActivated: [
    "Welcome to our lending program. The terms are... flexible.",
    "Sign here, here, and here. Just kidding, we don't do paperwork.",
    "Tony will be in touch about the repayment schedule.",
    "Smart choice. Well, not 'smart' exactly, but a choice.",
    "The house always extends credit. The house always collects.",
    "You're officially playing with money that doesn't exist. My favorite kind.",
  ],
}
